[package]
name = "k2_basecamp"
version = "0.10.2"
description = "CTAPI adpater for the gematik Konnektor"
authors = ["Christian Fochler <fochler@ehealhtexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-basecamp.git"
publish = false
build = "build.rs"

[lib]
name = "ctehxk2"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.6"
envy = "0.3"
futures = "0.1"
hyper = "0.11"
lazy_static = "0.2"
log = "0.3"
log4rs = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"

[build-dependencies]
moz-cheddar = "0.4"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
FileDescription = "K2 adapter for CTAPI"
FileVersion = "0.10.2"
LegalCopyright = "eHealthExperts GmbH. All rights reserved."
OriginalFilename = "ctehxk2.dll"
ProductName = "K2 basecamp"
ProductVersion = "0.10.2"
